export * from './base';
export * from './wechat';
export * from './zhihu';
export * from './juejin';
export * from './csdn';
export * from './jianshu';
export * from './cnblogs';
export * from './51cto';
export * from './tencent-cloud';
export * from './aliyun';
export * from './segmentfault';
export * from './bilibili';
export * from './oschina';

import { registry } from './base';
import { wechatAdapter } from './wechat';
import { zhihuAdapter } from './zhihu';
import { juejinAdapter } from './juejin';
import { csdnAdapter } from './csdn';
import { jianshuAdapter } from './jianshu';
import { cnblogsAdapter } from './cnblogs';
import { cto51Adapter } from './51cto';
import { tencentCloudAdapter } from './tencent-cloud';
import { aliyunAdapter } from './aliyun';
import { segmentfaultAdapter } from './segmentfault';
import { bilibiliAdapter } from './bilibili';
import { oschinaAdapter } from './oschina';

// 注册所有适配器
registry.register(wechatAdapter);
registry.register(zhihuAdapter);
registry.register(juejinAdapter);
registry.register(csdnAdapter);
registry.register(jianshuAdapter);
registry.register(cnblogsAdapter);
registry.register(cto51Adapter);
registry.register(tencentCloudAdapter);
registry.register(aliyunAdapter);
registry.register(segmentfaultAdapter);
registry.register(bilibiliAdapter);
registry.register(oschinaAdapter);
